import { candidate } from "../types/types";


export const candidates: candidate[] = [
  {
    id: 1,
    org: "OSIS",
    nopil: 1,
    nama_ketua: "Vincent Dennis Karmawan",
    nama_wakil: "Vivian",
    misi: ["Menjadikan OSIS SMK PLUS PELITA NUSANTARA yang bertakwa terhadap Tuhan YME, serta menjunjung tinggi toleransi antar umat beragama",
      "Mengembangkan berbagai kegiatan yang meningkatkan prestasi sekolah dengan  mendukung minat dan bakat siswa/i dalam bidang akademik maupun non-akademik",
      "Mendorong kerjasama antar siswa/i melalui berbagai kegiatan dari setiap event-event atau perlombaan program kerja OSIS yang membangun kebersamaan dan solidaritas",
      "Mewujudkan OSIS yang transparan dan akuntabel dengan melibatkan siswa dalam pengambilan keputusan penting",
      "Meningkatkan soft skill siswa/i sehingga mahir berbicara didepan umum dalam berbahasa Inggris maupun menyampaikan pendapat-pendapat positif dan berjiwa kepemimpinan"],
    proker: {
      Jangka_Pendek: ["Mengadakan Turnamen E-sport",
        "Mengadakan Latihan Dasar Kepemimpinan Siswa (LDKS)",
        "Mengadakan event FIESTA (Festival of Indonesian & English Student Talent) sesuai dengan minat dan bakat siswa/i",
        "Mengadakan pengecekan kelengkapan atribut setiap Senin pagi didepan lorong dan Razia rambut beserta make up bersama tim guru Bimbingan dan Konseling demi menertibkan dan meningkatkan kedisiplinan siswa/i"],
      Jangka_Panjang: ["Memperingati Hari Besar Nasional dan Keagamaan",
        "Mengadakan PORSENI (Pekan Olahraga Seni)",
        "Membantu Menyukseskan Upacara pengibaran Bendera Merah Putih di setiap hari Senin"],
    },
    visi: "Menjadikan OSIS sebagai organisasi yang aktif dan terpelajar dalam menampung ide, kreativitas, dan aspirasi siswa untuk mewujudkan SMK Plus Pelita Nusantara yang berprestasi, berintegritas, berjiwa entrepreneur, dan religius.",
  },
  {
    id: 2,
    org: "MPK",
    nopil: 1,
    nama_ketua: "Haifa Tsabita",
    nama_wakil: "Bryan Caesar Latuhamina",
    misi: ["Memaksimalkan MPK sebagai peran aktif dalam menampung dan menyalurkan aspirasi warga sekolah SMK Plus Pelita Nusantara",
      "Meningkatkan kinerja MPK dalam pengawasan",
      "Memperkuat undang-undang AD, ART dan GBHO MPK/OSIS",
      "Menciptakan komunikasi yang terbuka antar sesama anggota"],
    proker: {
      Jangka_Pendek: ["Menampung aspirasi warga sekolah melalui Gform dan menyalurkan setiap 1 bulan sekali", "Melaksanakan rapat rutin pengurus MPK setiap 1 bulan sekali",
        "Melaksanakan rapat evaluasi OSIS yang bersifat insidental",
        "Mengadakan rapat untuk ketua/perwakilan Talent Day dan Ekstrakurikuler setiap 3 bulan"],
      Jangka_Panjang: ["Melaksanakan Musyawarah Kerja (MUKER)",
        "Melaksanakan Musyawarah Besar (MUBES)",
        "Melaksanakan Laporan Pertanggung Jawaban (LPJ)",
        "Membuat Komisi Pemilihan Organisasi Pelajar (KPOP)"],
    },
    visi: "Memaksimalkan peran MPK yang efektif dan transparan untuk mengoptimalkan seluruh kegiatan organisasi pelajar.",
  },
  {
    id: 3,
    org: "OSIS",
    nopil: 2,
    nama_ketua: "Riyandi Feriansyah Putra",
    nama_wakil: "Nurul Agustian Ramadani",
    misi: ["Meningkatkan keimanan serta ketaqwaan siswa/i terhadap Tuhan Yang Maha Esa",
      "Mengembangkan minat serta bakat siswa/i dalam bidang akademik maupun Non-akademik",
      "Melanjutkan dan mengembangkan program kerja OSIS yang sudah terlaksanakan ataupun yang belum terlaksanakan",
      "Mendorong siswa/i SMK Plus Pelita Nusantara untuk mengembangkan jiwa kewirausahaan dan memberikan dukungan bagi ide-ide bisnis kreatif",
      "Merealisasikan aspirasi siswa/i yang mengarah kepada hal yang positif",
      "Meningkatkan literasi siswa/i melalui kegiatan membaca"],
    proker: {
      Jangka_Pendek: ["Mengadakan Pesta Pora Warga Penus",
        "Menjalin hubungan organisasi, ekstrakurikuler, dan talent day",
        "Mengadakan pelatihan keorganisasian",
        "Mengadakan sistem volunteer pada setiap acara yang akan dijalankan",
        "Mengadakan Acara 'Our Language Is Our Identity"],
      Jangka_Panjang: ["Membantu menyukseskan upacara bendera di hari Senin",
        "Melaksanakan OSIS peduli yang bertujuan untuk membantu orang yang terkena musibah",
        "Memperingati hari keagamaan, hari nasional, serta hari besar lainnya",
        "Mengadakan kegiatan 'Together We Recycle, Together We Save The Earth'",
        "Mengadakan turnamen E-sport internal maupun eksternal"],
    },
    visi: "Mewujudkan OSIS sebagai organisasi yang berintegritas untuk terciptanya generasi yang unggul dan kreatif.",
  },
  {
    id: 4,
    org: "MPK",
    nopil: 2,
    nama_ketua: "Shoffi Dinda Rosalam",
    nama_wakil: "Muhammad Imam Aulia",
    misi: ["Mengoptimalkan tugas pokok dan fungsi MPK dalam pengawasan kinerja OSIS",
      "Meningkatkan Kerjasama antara OSIS dan MPK untuk mencapai tujuan bersama",
      "Mengoptimalkan ranah SMK Plus Pelita Nusantara dalam membantu menangani Ekstrakurikuler dan Talentday",
      "Menjadikan MPK sebagai wadah untuk merealisasikan aspirasi warga sekolah SMK Plus Pelita Nusantara"],
    proker: {
      Jangka_Pendek: ["Mengadakan diskusi dari masing-masing Ekstrakurikuler dan Talentday SMK Plus Pelita Nusantara setiap 3 bulan sekali",
        "Mengadakan rapat rutin evaluasi MPK setiap 3 bulan sekali",
        "Mengadakan rapat rutin evaluasi OSIS setiap 1 bulan sekali",
        "Menampung aspirasi siswa/i SMK Plus Pelita Nusantara melalui Gform setiap 1 bulan sekali"],
      Jangka_Panjang: ["Melaksanakan MUKER (Musyawarah Kerja)",
        "Melaksanakan MUBES (Musyawarah Besar)",
        "Melaksanakan Sidang Pleno",
        "Membuat Laporan Pertanggung Jawaban (LPJ)",
        "Membuat Komisi Pemilihan Organisasi Pelajar (KPOP)"],
    },
    visi: "Mengoptimalkan fungsi MPK SMK Plus Pelita Nusantara yang Demokratis demi terwujudnya organisasi yang berkualitas.",
  },
]
